language: scala

scala:
   - 2.11.8

jdk:
   - oraclejdk8


cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/

script:
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts .jvmopts clean coverage test tut


after_success:
  - sbt coverageReport
  - sbt coverageAggregate
  - sbt codacyCoverage
